force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer Bank</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Question_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Bank</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Data_type__c.field-meta.xml
<CustomField>
    <fullName>Question_Data_type__c</fullName>
    <label>Question Data type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Radio Box</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>This object is used for holding Question Answer Options</description>
    <label>Question Answer Option</label>
    <nameField>
        <displayFormat>QAO-{00000}</displayFormat>
        <label>Question Answer Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Data_Type__c</fullName>
    <formula>TEXT(Question__r.Question_Data_type__c)</formula>
    <label>Question Data Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/Question_Bank__c.object-meta.xml
<CustomObject>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{000000}</displayFormat>
        <label>Question Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Bank__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CreateNewQuestionCtrlTest.cls
@isTest 
public class CreateNewQuestionCtrlTest {
    @testSetup static void setUpData() 
    { 
        Question_Bank__c questionBank1 = testFactory.createQuestionBank('Demo question', null, true);
        
        Question__c ques1 = testFactory.createQuestion(questionBank1.Id, null, 'Text', true);
        ques1.Question_Text__c = 'Demo question';
        Answer__c ans = testFactory.createAnswer(null, 'Demo answer text', true, true);
        Question_Answer_Option__c quesAnsOpt1 = testFactory.createQuestionAnswerOption(ans.Id, ques1.Id, null, 'demo', true);
    }
    static testmethod void testCheckDuplicateAndEditable(){
        Question__c ques = [SELECT Id,Question_Bank__c, Question_Text__c, Question_Data_type__c FROM Question__c limit 1];
        Answer__c ans = [SELECT Id FROM Answer__c limit 1];
        
        List<String> ansList = new List<String>();
        ansList.add(ans.Id);
        
        String resp = CreateNewQuestionCtrl.checkDuplicate(ques.Question_Bank__c, ques.Question_Data_type__c, ansList);
        system.debug('###' +resp);
        //CreateNewQuestionCtrl.checkDuplicate(ques.Question_Text__c, ques.Question_Data_type__c, null);
        system.assertEquals('Duplicate', resp);
        
   
    }
    
    static testmethod void testCreateQuestion(){
        Question_Bank__c questionBank = [SELECT Id FROM Question_Bank__c limit 1];
        Question__c ques = testFactory.createQuestion(questionBank.Id, null, 'Text', false);
        //ques.Question_Text__c = 'Test Question 2';
       // CreateNewQuestionCtrl.checkDuplicate(questionBank.Id, ques.Question_Data_type__c, null);

        String quesId = CreateNewQuestionCtrl.createQuestion(ques);
        System.assertNotEquals(quesId, null, 'Question ID should not be null');
      //System.assertEquals(ques.Id, quesId);
    }
    
    static testmethod void testUpdateQuestion(){
        Question__c ques = [SELECT Id, Question_Data_type__c FROM Question__c limit 1];
        String quesId = CreateNewQuestionCtrl.updateQuestion(ques);
        system.assertEquals(ques.Id, quesId);
    }
    
    static testmethod void testCreateAnsOptions(){
        Question_Bank__c questionBank1 = testFactory.createQuestionBank('Demo question12', null, true);
        Question__c ques1 = testFactory.createQuestion(questionBank1.Id, null, 'Text', true);
        
        Question_Bank__c questionBank2 = testFactory.createQuestionBank('Demo question1212', null, true);
        Question__c ques2 = testFactory.createQuestion(questionBank2.Id, null, 'Text', true);
        Answer__c ans = [SELECT Id FROM Answer__c limit 1];
        
        Question_Answer_Option__c quesAnsOpt1 = testFactory.createQuestionAnswerOption(ans.Id, ques1.Id, null, 'demo1234', false);
        Question_Answer_Option__c quesAnsOpt2 = testFactory.createQuestionAnswerOption(ans.Id, ques2.Id, null, 'demo1234', false);
        
        List<Question_Answer_Option__c> quesAnsOptList = new List<Question_Answer_Option__c>();
        quesAnsOptList.add(quesAnsOpt1);
        quesAnsOptList.add(quesAnsOpt2);
        system.debug(quesAnsOptList[0].question__c);
        system.debug(quesAnsOptList[1].question__c);
        system.debug(quesAnsOptList);
        CreateNewQuestionCtrl.createAnsOptions(quesAnsOptList, true);   
        system.assertEquals('demo1234', quesAnsOptList[0].Question_Text__c);
    }
    
    static testmethod void testGetQuestionData(){
        Question__c ques = [SELECT Id, Question_Data_type__c FROM Question__c limit 1];
        CreateNewQuestionCtrl.getQuestionData(ques.Id);
        CreateNewQuestionCtrl.checkEditable(ques.Id);
        system.assertEquals('Text', CreateNewQuestionCtrl.getQuestionData(ques.Id).quesDataType);
    }
}