force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer Bank</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Answer_Options__c.field-meta.xml
<CustomField>
    <fullName>Answer_Options__c</fullName>
    <label>Answer Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Question_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Bank</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>This object is used for holding Question Answer Options</description>
    <label>Question Answer Option</label>
    <nameField>
        <displayFormat>QAO-{00000}</displayFormat>
        <label>Question Answer Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/Question_Bank__c.object-meta.xml
<CustomObject>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{000000}</displayFormat>
        <label>Question Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Bank__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QuestionsControllerTest.cls
/**
 * Test class for QuestionsController.
 * It verifies functionality for retrieving, deleting questions, and their associated answer options.
 */
@isTest
public with sharing class QuestionsControllerTest {
    
    // Creates test data for Question_Bank, Question, Answer, and Question_Answer_Option
    @testSetup static void setupMaster(){
        Question_Bank__c qbTestData = testFactory.createQuestionBank('Test Question', null, true);
        Question__c quesTestData = testFactory.createQuestion(qbTestData.Id, null, 'Radio Box', false);
        quesTestData.Question_Text__c = 'Test Question';
        quesTestData.Answer_Options__c = 'AnsOption1|AnsOption2';
        quesTestData.Active__c = true;
        insert quesTestData;

        Answer__c ansTestData = testFactory.createAnswer(null, 'Test Answer', true, true);
        Question_Answer_Option__c qaoTestData = testFactory.createQuestionAnswerOption(ansTestData.Id, quesTestData.Id, null, null, true);
    }

    // Tests retrieval of all questions and their answer options, and deletes a question
    static testMethod void testGetAllQuestions() {
        List<Question__c> quesList = QuestionsController.getAllQuestions(true);
        Integer quesCount = quesList.size();
        System.assertEquals(quesCount, 1);

        Question__c ques = [SELECT Id, Name FROM Question__c LIMIT 1];
        List<Question_Answer_Option__c> qaoList = QuestionsController.getAnswerOptions(ques.Id);
        Integer qaoCount = qaoList.size();
        System.assertEquals(qaoCount, 1);

        QuestionsController.deleteQuestion(ques.Id);
    }
}