force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer Bank</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <label>Answer Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnswerSelectionController.cls
public with sharing class AnswerSelectionController {
    @AuraEnabled(cacheable=true)
    public static List<Answer__c> getActiveAnswers(String searchTerm){
        List<Answer__c> answerList = new List<Answer__c>();
        String searchTermConverted = '';
        if((searchTerm==null || searchTerm=='')){
            answerList = [select Id, Answer_Text__c from Answer__c where Active__c=true WITH SECURITY_ENFORCED order by lastmodifieddate desc];
        }else{
            searchTermConverted = '%'+searchTerm+'%';
            for(Answer__c ans:[select Id, Answer_Text__c from Answer__c where Active__c=true and Answer_Text__c like :searchTermConverted WITH SECURITY_ENFORCED order by lastmodifieddate desc]){
                answerList.add(ans);
            }
        }
        System.debug('answerList ## '+answerList);
        return answerList;
    }
}