force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer Bank</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Question__c/Assessment_Question__c.object-meta.xml
<CustomObject>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>AQ-{00000}</displayFormat>
        <label>Assessment Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Question__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Outcome__c/Outcome__c.object-meta.xml
<CustomObject>
    <label>Outcome</label>
    <nameField>
        <label>Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Outcome__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Outcomes</relationshipLabel>
    <relationshipName>Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Outcome__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Outcome__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Answer_Options__c.field-meta.xml
<CustomField>
    <fullName>Answer_Options__c</fullName>
    <label>Answer Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Question_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Bank</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/Question_Bank__c.object-meta.xml
<CustomObject>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{000000}</displayFormat>
        <label>Question Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Bank__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Question</label>
    <referenceTo>Assessment_Question__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <referenceTo>Outcome__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OutcomeCmpControllerTest.cls
@isTest
public with sharing class OutcomeCmpControllerTest {
    @testSetup static void setupMaster(){
    //    Account accTestData=TestFactory.createAccount('ACDHS', 'Service Provider',true);
    /*    Service__c serviceTestData=TestFactory.createService('Test Service',null,true);
        SP_Service__c spserviceTestData=TestFactory.createSPService(accTestData.Id,serviceTestData.Id,null,true);
        Referral__c refTestData=TestFactory.createReferral('New', null, true);
        Client_Service__c asTestData = TestFactory.createClientService(spserviceTestData.Id,refTestData.Id,null,true);*/
        Assessment__c assessmentTestData=TestFactory.createAssessment(null, 'Test Assessment',true);
        Outcome__c outcomeASTestData=TestFactory.createOutcome(null, 'Test Outcome Assigned Service',assessmentTestData.Id,false);
     //   outcomeASTestData.Record_Id__c=asTestData.Id;
        outcomeASTestData.Assessment_Date__c=system.today();
        insert outcomeASTestData;
        Outcome__c outcomeRefTestData=TestFactory.createOutcome(null, 'Test Outcome Referral',assessmentTestData.Id,false);
  //      outcomeRefTestData.Record_Id__c=refTestData.Id;
        outcomeRefTestData.Status__c='Pending';
        outcomeRefTestData.Assessment_Date__c=system.today();
        insert outcomeRefTestData;

        Question_Bank__c qbTestData=TestFactory.createQuestionBank('Test Question',null,true);
        Question__c quesTestData=TestFactory.createQuestion(qbTestData.Id,null,'Radio Box',false);
        quesTestData.Question_Text__c='Test Question';
        quesTestData.Answer_Options__c='AnsOption1|AnsOption2';
        insert quesTestData;
        //Answer__c ansTestData=TestFactory.createAnswer();
        Assessment_Question__c ansQuesTestData=TestFactory.createAssessmentQuestion(null, quesTestData.Id, assessmentTestData.id, 'field Updation', false, 1, 1, 'General', 'Complaint Information', true);
        Response__c resposeTestData1=TestFactory.createResponse(null,assessmentTestData.Id,outcomeRefTestData.Id,false);
        resposeTestData1.Assessment_Question__c=ansQuesTestData.Id;
        resposeTestData1.Sequence__c='1';
        insert resposeTestData1;

        Response__c resposeTestData2=TestFactory.createResponse(null,assessmentTestData.Id,outcomeRefTestData.Id,false);
        resposeTestData2.Assessment_Question__c=ansQuesTestData.Id;
        resposeTestData2.Sequence__c='20';
        insert resposeTestData2;
        Response__c resposeTestData3=TestFactory.createResponse(null,assessmentTestData.Id,outcomeRefTestData.Id,false);
        resposeTestData3.Assessment_Question__c=ansQuesTestData.Id;
        resposeTestData3.Sequence__c='300';
        insert resposeTestData3;

        outcomeRefTestData.Status__c='Complete';

        update outcomeRefTestData;
    }

    static testMethod void testGetOutcomes()
    {
        Outcome__c outcomeTest= [select id, name, Record_Id__c, Status__c from Outcome__c where name=:'Test Outcome Referral' limit 1];
        List <Outcome__c> outcomeList= new List<Outcome__c>();
        outcomeList=OutcomeCmpController.getOutcomes(outcomeTest.Record_Id__c);
        Integer outcomeCount=outcomeList.size();
        system.assertEquals(outcomeCount, 1);
    }
    static testMethod void testGetOutcomeDetails()
    {
        Outcome__c outcomeASTest= [select id, name, Record_Id__c from Outcome__c where name='Test Outcome Assigned Service' limit 1];
        OutcomeCmpController.OutcomeDetailsWrapper result = OutcomeCmpController.getOutcomeDetails(outcomeASTest.Id,'Account');
        System.assertNotEquals(null, result, 'The result should not be null');

    //    Outcome__c outcomeRefTest= [select id, name, Record_Id__c from Outcome__c where name='Test Outcome Referral' limit 1];
    //    OutcomeCmpController.getOutcomeDetails(outcomeRefTest.Id,'caresp__Outcome__c');
    }
    static testMethod void testGetResponses()
    {
        Outcome__c outcomeRefTest= [select id, name, Record_Id__c from Outcome__c where name='Test Outcome Referral' limit 1];
        List<OutcomeCmpController.QuestionsWrapper> result = OutcomeCmpController.getResponses(outcomeRefTest.Id);
        System.assertNotEquals(null, result, 'The response list should not be null');
        
    }
}