force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer Bank</label>
    <nameField>
        <displayFormat>ANS-{00000}</displayFormat>
        <label>Answer Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <label>Answer Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Answer_Options__c.field-meta.xml
<CustomField>
    <fullName>Answer_Options__c</fullName>
    <label>Answer Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Category__c.field-meta.xml
<CustomField>
    <fullName>Question_Category__c</fullName>
    <label>Question Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Data_type__c.field-meta.xml
<CustomField>
    <fullName>Question_Data_type__c</fullName>
    <label>Question Data type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Radio Box</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/Question_Answer_Option__c.object-meta.xml
<CustomObject>
    <description>This object is used for holding Question Answer Options</description>
    <label>Question Answer Option</label>
    <nameField>
        <displayFormat>QAO-{00000}</displayFormat>
        <label>Question Answer Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <formula>Answer__r.Answer_Text__c</formula>
    <label>Answer Text</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Data_Type__c</fullName>
    <formula>TEXT(Question__r.Question_Data_type__c)</formula>
    <label>Question Data Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question_Answer_Option__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/QuestionsController.cls
public with sharing class QuestionsController {
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getAllQuestions(Boolean active){
        return [select Id, Question_Text__c, Question_Data_Type__c, Question_Category__c, Answer_Options__c, Active__c from Question__c where Active__c =: active WITH SECURITY_ENFORCED order by createddate desc];
    }

    @AuraEnabled
    public static List<Question_Answer_Option__c> getAnswerOptions(String quesId){
        System.debug('Ques ID # '+quesId);
        return [select Id, Answer__c, Answer_Text__c, Question__c, Question_Text__c from Question_Answer_Option__c where Question__c =:quesId WITH SECURITY_ENFORCED];
    }

    @AuraEnabled
    public static void deleteQuestion(String questionId){
        System.debug('question deletable>> ' + Schema.sObjectType.caresp__Question__c.isDeletable());
        if(String.isNotBlank(questionId)){
            if(Schema.sObjectType.caresp__Question__c.isDeletable()) {//added by sg
            delete as user [select Id from Question__c where Id = :questionId WITH SECURITY_ENFORCED];
            }
        }
    }
}