force-app/main/default/objects/Assessment_Question__c/Assessment_Question__c.object-meta.xml
<CustomObject>
    <label>Assessment Question</label>
    <nameField>
        <displayFormat>AQ-{00000}</displayFormat>
        <label>Assessment Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Assessment Questions</relationshipLabel>
    <relationshipName>Assessment_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Question</label>
    <referenceTo>Assessment_Question__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ResponseTriggerHandler.cls
public with sharing class ResponseTriggerHandler implements ITriggerHandler
{
	public void BeforeInsert(List<SObject> newItems)
    {
		updateQuestionTextOnResponse((List<Response__c>)newItems);        
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems)
    {}  
    
    public void BeforeDelete(Map<Id, SObject> oldItems)
    {}
    
    public void AfterInsert(Map<Id, SObject> newItems)
    {
        
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems)
    {}
    
    public void AfterDelete(Map<Id, SObject> oldItems)
    {}
    
    public void AfterUndelete(Map<Id, SObject> oldItems)
    {}
    

    
    public static void updateQuestionTextOnResponse(List<caresp__Response__c>listResp)
    {
        List<String> asQuesIdList = new List<String>();
        for(caresp__Response__c resp:listResp){
            asQuesIdList.add(resp.caresp__Assessment_Question__c);
        }
        
        Map<Id, caresp__Assessment_Question__c> asQuesMap = new Map<Id, caresp__Assessment_Question__c>([select Id, Question__r.Question_Text__c from Assessment_Question__c where Id in :asQuesIdList WITH SECURITY_ENFORCED]);
    
        for(caresp__Response__c resp:listResp){
            if(asQuesMap.get(resp.caresp__Assessment_Question__c)!=null){
             	resp.caresp__Question_Text__c = asQuesMap.get(resp.caresp__Assessment_Question__c).caresp__Question__r.caresp__Question_Text__c;   
            }
        }
    }
    
    
}