force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This object is for holding the Question bank</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Bank__c.field-meta.xml
<CustomField>
    <fullName>Question_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Bank</label>
    <referenceTo>Question_Bank__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Bank__c/Question_Bank__c.object-meta.xml
<CustomObject>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{000000}</displayFormat>
        <label>Question Bank ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Bank__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomLookupLwcControllerTest.cls
@isTest
public class CustomLookupLwcControllerTest {
    @isTest
    static void testFetchLookupData() {
        Question_Bank__c testQuesBank = TestFactory.createQuestionBank('Test Question Bank', '', true);
        Question__c testQuestion = TestFactory.createQuestion(testQuesBank.Id, '', 'Text', false);
        testQuestion.Question_Text__c='Test';
        insert testQuestion;
        List<Question__c> result = CustomLookupLwcController.fetchLookupData('Test', 'Question__c', 'Question_Text__c');
        System.assertEquals(1, result.size());
        System.assertEquals(testQuestion.Id, result[0].Id);
    }

    @isTest
    static void testFetchDefaultRecord() {
        Question_Bank__c testQuesBank = TestFactory.createQuestionBank('Test Question Bank', '', true);
        Question__c testQuestion = TestFactory.createQuestion(testQuesBank.Id, '', 'Text', false);
        testQuestion.Question_Text__c='Test';
        insert testQuestion;
        Question__c result = (Question__c) CustomLookupLwcController.fetchDefaultRecord(testQuestion.Id, 'Question__c', 'Question_Text__c');
        System.assertNotEquals(null, result);
        System.assertEquals(testQuestion.Id, result.Id);
    }
}