force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Outcome__c/Outcome__c.object-meta.xml
<CustomObject>
    <label>Outcome</label>
    <nameField>
        <label>Outcome Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outcomes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Outcome__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Outcomes</relationshipLabel>
    <relationshipName>Outcomes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssessmentTriggerHelperTest.cls
@isTest
public with sharing class AssessmentTriggerHelperTest {
    @testSetup static void setupMaster(){
        Assessment__c assessmentTestData=TestFactory.createAssessment(null, 'Test Assessment',true);
      //  Assessment__c assessmentTestData2=TestFactory.createAssessment(null, 'Test Assessment2',true);
        Outcome__c outcomeTestData=TestFactory.createOutcome(null, 'Test Outcome1',assessmentTestData.Id,true);
    }
    static testMethod void testCheckAssessmentInUse(){
        
        try {
            Assessment__c assessmentData=[select id from Assessment__c limit 1];
        //    update assessmentData;
            delete assessmentData;
        } catch (Exception e) {
            system.assert(e.getMessage().contains('This Assessment cannot be deleted.'));
        }
 /*       Assessment__c assessmentData2=[select id from Assessment__c where name='Test Assessment2' limit 1];
        delete assessmentData2;
        undelete assessmentData2;*/
    }
}